FROM ubuntu:18.04 

RUN apt-get update && apt-get -y install python3.6 -y && apt-get install -y python3-pip

ADD ./Dockerfiles/requirements.txt ./requirements.txt
RUN pip3 install -r requirements.txt

RUN useradd -ms /bin/bash john && echo "john:john" | chpasswd && adduser john sudo


ADD ./Scrape_Exploit /home/john/Project/CVE_crawler/Scrape_Exploit/
WORKDIR /home/john/Project/CVE_crawler/Scrape_Exploit/
RUN chown -R john:john /home/john/Project
RUN chmod 755 /home/john/Project
USER john
CMD [ "sleep", "9223372036854775807" ]