FROM ubuntu:18.04 

RUN apt-get update && apt-get -y install python3.6 -y && apt-get install -y python3-pip && apt-get install -y python3-dev

ENV LANG C.UTF-8
ADD ./Dockerfiles/requirements.txt ./requirements.txt
RUN pip3 install -r requirements.txt

RUN useradd -ms /bin/bash john && echo "john:john" | chpasswd && adduser john sudo
ADD ./API_Calls/ /home/john/Project/CVE_crawler/API_Calls
WORKDIR /home/john/Project/CVE_crawler/API_Calls
RUN chown -R john:john /home/john/Project
RUN chmod 755 /home/john/Project
USER john

CMD [ "sleep", "9223372036854775807" ]